#!/usr/bin/env bash
# Update the package list
sudo apt update

sudo apt install -y nginx

sudo service nginx start

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo service nginx restart

# Create a simple HTML page with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.html
