#!/usr/bin/env bash
# Step 1: Install Nginx web server (assuming you have the 1-install_nginx_web_server script)
source ./1-install_nginx_web_server.sh

echo 'Hello World!' > /var/www/html/index.nginx-debian.html
add="server {
        listen 80;
        listen [::]:80;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
	location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

echo -e "$add" > /etc/nginx/sites-available/redirect
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

nginx -t

systemctl reload nginx
