#!/usr/bin/env bash
# This is all about the redirection

sudo apt update -y
sudo apt install nginx -y
sudo chown \$USER:\$USER /etc/nginx/sites-available/
mkdir -p /var/www/html
sudo chmod -R 755 /var/www
sudo chown -R \$USER:\$USER /var/www/html
echo "Hello World!" > /var/www/html/index.html

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }

        if (\$request_filename ~ redirect_me){
                rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}" > /etc/nginx/sites-available/default
sudo systemctl restart nginx
