#!/usr/bin/env bash
#this is another comment don't ask me

x=0

while [ $x -lt 10 ]
do
	if [ $x = 3 ]
	then
		echo "bad luck"
	elif [ $x = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$((x+1))
done
