#!/usr/bin/env bash
# eih mhen no comment for now

x=0
i=1
echo "Hour: $x"

while [ $i -lt 10 ]
do
	while [ $x -lt 59 ]
	do
		x=$((x+1))
		echo "$x"
		if [ $x -eq 59 ]
		then
			echo "Hour: $i"
		fi
	done
	echo "$i"
	i=$((i+1))
done
