#!/usr/bin/env bash
# Checking files
filename="./school"
if [ -e "$filename" ]; then
    echo "school file exists"
    if [ ! -s "$filname" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$filename" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
