#!/usr/bin/env bash
# Checking files
filename="./school"
ln=$(wc -l "$filename" | awk '{print $1}')

if [ -e "$filename" ]; then
    echo "school file exists"
    if [ "$ln" -eq 0 ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$filename" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
