#!/usr/bin/env bash
#another comment look for 
cp /etc/hosts /etc/hosts.new
echo "
127.0.0.2       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.28     50690c12925b
8.8.8.8		facebook.com
" > hosts.new
cp -f ~/hosts.new /etc/hosts
