#!/usr/bin/env bash
#another comment look for 
cp etc/hosts ~/hosts.new
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/newhosts /etc/newhost
