#!/usr/bin/env bash
#another comment look for 
cp /etc/hosts /etc/hosts.new
sed -i '1s/^127[0-9.]*\s/127.0.0.2       /' /etc/hosts.new
echo "8.8.8.8		facebook.com" >> /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
